<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Searchcolumnsets', 'doctrine');

/**
 * BaseSearchcolumnsets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $defaultset
 * @property string $name
 * @property string $jsonfields
 * 
 * @method integer          getId()         Returns the current record's "id" value
 * @method integer          getDefaultset() Returns the current record's "defaultset" value
 * @method string           getName()       Returns the current record's "name" value
 * @method string           getJsonfields() Returns the current record's "jsonfields" value
 * @method Searchcolumnsets setId()         Sets the current record's "id" value
 * @method Searchcolumnsets setDefaultset() Sets the current record's "defaultset" value
 * @method Searchcolumnsets setName()       Sets the current record's "name" value
 * @method Searchcolumnsets setJsonfields() Sets the current record's "jsonfields" value
 * 
 * @package    AlfrescoClient
 * @subpackage model
 * @author     Dominik Danninger
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSearchcolumnsets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('searchcolumnsets');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('defaultset', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('jsonfields', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}