<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AlfrescoAccount', 'doctrine');

/**
 * BaseAlfrescoAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_token
 * @property timestamp $last_login
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method string          getUserToken()  Returns the current record's "user_token" value
 * @method timestamp       getLastLogin()  Returns the current record's "last_login" value
 * @method timestamp       getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()  Returns the current record's "updated_at" value
 * @method AlfrescoAccount setId()         Sets the current record's "id" value
 * @method AlfrescoAccount setUserToken()  Sets the current record's "user_token" value
 * @method AlfrescoAccount setLastLogin()  Sets the current record's "last_login" value
 * @method AlfrescoAccount setCreatedAt()  Sets the current record's "created_at" value
 * @method AlfrescoAccount setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    AlfrescoClient
 * @subpackage model
 * @author     Dominik Danninger
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAlfrescoAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alfresco_account');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('user_token', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('last_login', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}