<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Viewerrelations', 'doctrine');

/**
 * BaseViewerrelations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nodeid
 * @property string $viewernode
 * @property string $viewerurl
 * @property blob $viewercontent
 * @property string $md5sum
 * 
 * @method integer         getId()            Returns the current record's "id" value
 * @method string          getNodeid()        Returns the current record's "nodeid" value
 * @method string          getViewernode()    Returns the current record's "viewernode" value
 * @method string          getViewerurl()     Returns the current record's "viewerurl" value
 * @method blob            getViewercontent() Returns the current record's "viewercontent" value
 * @method string          getMd5sum()        Returns the current record's "md5sum" value
 * @method Viewerrelations setId()            Sets the current record's "id" value
 * @method Viewerrelations setNodeid()        Sets the current record's "nodeid" value
 * @method Viewerrelations setViewernode()    Sets the current record's "viewernode" value
 * @method Viewerrelations setViewerurl()     Sets the current record's "viewerurl" value
 * @method Viewerrelations setViewercontent() Sets the current record's "viewercontent" value
 * @method Viewerrelations setMd5sum()        Sets the current record's "md5sum" value
 * 
 * @package    AlfrescoClient
 * @subpackage model
 * @author     Dominik Danninger
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseViewerrelations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('viewerrelations');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('nodeid', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('viewernode', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('viewerurl', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('viewercontent', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('md5sum', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}