<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Alfrescofavorites', 'doctrine');

/**
 * BaseAlfrescofavorites
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nodename
 * @property string $nodeid
 * @property string $nodetype
 * @property string $userkey
 * 
 * @method integer           getId()       Returns the current record's "id" value
 * @method string            getNodename() Returns the current record's "nodename" value
 * @method string            getNodeid()   Returns the current record's "nodeid" value
 * @method string            getNodetype() Returns the current record's "nodetype" value
 * @method string            getUserkey()  Returns the current record's "userkey" value
 * @method Alfrescofavorites setId()       Sets the current record's "id" value
 * @method Alfrescofavorites setNodename() Sets the current record's "nodename" value
 * @method Alfrescofavorites setNodeid()   Sets the current record's "nodeid" value
 * @method Alfrescofavorites setNodetype() Sets the current record's "nodetype" value
 * @method Alfrescofavorites setUserkey()  Sets the current record's "userkey" value
 * 
 * @package    AlfrescoClient
 * @subpackage model
 * @author     Dominik Danninger
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAlfrescofavorites extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alfrescofavorites');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('nodename', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('nodeid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('nodetype', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('userkey', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}