<?php

/**
 * Allowedtypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    AlfrescoClient
 * @subpackage model
 * @author     Dominik Danninger
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Allowedtypes extends BaseAllowedtypes
{

}